"""Integration tests for the gate-all single-process facade (pptx_tool.py).

The fixture deck is generated by the real Node pipeline so it passes the
OpenXML SDK package validation that the package step performs.
"""

from __future__ import annotations

import hashlib
import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SKILL_SCRIPTS = ROOT / "skills" / "sp-deck" / "scripts"
PPTX_TOOL = ROOT / "scripts" / "pptx_tool.py"

NODE_SCRIPT = r"""
const path = require('path');
const pluginRoot = process.argv[2];
const outPath = process.argv[3];
const PptxGenJS = require(path.join(pluginRoot, 'node_modules', 'pptxgenjs'));
const H = require(path.join(pluginRoot, 'scripts', 'pptx-helpers.js'));
const pptx = new PptxGenJS();
H.applyTokens(pptx, {}, 'chinese');
const pages = [
  { title: '标题一', body: '正文一' },
  { title: '标题二', body: '正文二' },
];
pages.forEach((page, index) => {
  const slide = pptx.addSlide();
  slide.addText(page.title, { x: 0.6, y: 0.5, w: 8.8, h: 0.6, fontSize: 33, bold: true });
  slide.addText(page.body, { x: 0.6, y: 1.6, w: 8.8, h: 2.0, fontSize: 22 });
  slide.addText('要点：判断与叙事不可外包 ' + (index + 1), {
    x: 0.6, y: 3.8, w: 8.8, h: 0.8, fontSize: 22,
  });
  slide.addText('AI 时代的课堂展示 · ' + (index + 1) + ' / 2', {
    x: 0.6, y: 5.15, w: 8.8, h: 0.3, fontSize: 11,
  });
});
pptx.writeFile({ fileName: outPath }).then(() => console.log('written'));
"""


def _load(name: str, path: Path):
    import importlib.util

    spec = importlib.util.spec_from_file_location(name, path)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


class GateAllTests(unittest.TestCase):
    def _make_fixture(self, root: Path) -> dict[str, Path]:
        deck = root / "gate-all-deck.pptx"
        script = root / "make-deck.js"
        script.write_text(NODE_SCRIPT, encoding="utf-8")
        subprocess.run(
            ["node", str(script), str(ROOT), str(deck)],
            cwd=str(ROOT),
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=120,
            check=True,
        )

        guard = _load("gate_all_spec_guard", SKILL_SCRIPTS / "slide_spec_guard.py")
        spec = root / "slide-spec.yaml"
        spec.write_text(
            "meta:\n"
            "  topic: Demo\n"
            "  duration_min: 8\n"
            "  citation_style: classroom\n"
            "slides:\n"
            "  - id: 1\n"
            "    title: 标题一\n"
            "    claim: 标题一\n"
            "    timing_sec: 240\n"
            "  - id: 2\n"
            "    title: 标题二\n"
            "    claim: 标题二\n"
            "    timing_sec: 240\n",
            encoding="utf-8",
        )
        report = root / "slide-spec-report.json"
        report.write_text(
            json.dumps(
                {
                    "valid": True,
                    "slide_spec_sha256": hashlib.sha256(spec.read_bytes()).hexdigest(),
                }
            ),
            encoding="utf-8",
        )
        lock = root / "spec-lock.json"
        guard.write_lock(
            lock,
            guard.make_lock(spec, report, revision=1, reason="gate-all test fixture"),
        )

        visual = root / "visual-review.json"
        slides = []
        for number, structure in enumerate(["statement", "process"], start=1):
            slides.append(
                {
                    "slide": number,
                    "visual_structure": structure,
                    "scores": {
                        "hierarchy": 8,
                        "focal_point": 8,
                        "composition": 8,
                        "visual_interest": 8,
                        "whitespace": 8,
                    },
                    "ai_template_feel": "none",
                    "issues": [],
                }
            )
        visual.write_text(
            json.dumps(
                {
                    "pptx_sha256": hashlib.sha256(deck.read_bytes()).hexdigest(),
                    "slides": slides,
                    "deck": {"issues": []},
                }
            ),
            encoding="utf-8",
        )
        return {"pptx": deck, "spec": spec, "lock": lock, "visual": visual}

    def _run_gate_all(self, root: Path, fixture: dict[str, Path]) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            [
                sys.executable,
                str(PPTX_TOOL),
                "gate-all",
                "--pptx", str(fixture["pptx"]),
                "--slide-spec", str(fixture["spec"]),
                "--spec-lock", str(fixture["lock"]),
                "--visual-report", str(fixture["visual"]),
                "--output-dir", str(root / "reports"),
                "--output", str(root / "gate-all-report.json"),
                "--json",
            ],
            cwd=str(ROOT),
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=180,
        )

    def test_gate_all_passes_a_clean_deck_and_writes_all_reports(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            fixture = self._make_fixture(root)
            result = self._run_gate_all(root, fixture)
            self.assertEqual(0, result.returncode, result.stdout[-2000:] + result.stderr[-2000:])

            merged = json.loads((root / "gate-all-report.json").read_text(encoding="utf-8"))
            self.assertTrue(merged["ok"])
            self.assertEqual("gate-all-v1", merged["gate_profile"])
            for name in ("package", "actual-content", "rendered", "quality"):
                self.assertTrue(merged["steps"][name]["ok"], f"{name} should pass: {merged['steps'][name]}")
                self.assertTrue((root / "reports" / merged["steps"][name]["report"]).is_file())
            # 单进程合并后，各门禁报告仍然独立存在且绑定同一 PPTX。
            self.assertEqual(
                merged["pptx_sha256"],
                hashlib.sha256(fixture["pptx"].read_bytes()).hexdigest(),
            )

    def test_gate_all_fails_closed_when_a_gate_blocks(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            fixture = self._make_fixture(root)
            # 换一个 9pt 文本且内容与 spec 不符的 deck：rendered（字号下限）与
            # actual-content（claim 回读）都会拦，quality 因 visual-review 绑定
            # 的哈希失效而失败——gate-all 必须 fail-closed（exit 2）。
            bad_deck = root / "bad-deck.pptx"
            bad_script = root / "make-bad-deck.js"
            bad_script.write_text(
                NODE_SCRIPT.replace("fontSize: 33", "fontSize: 9")
                .replace("fontSize: 22", "fontSize: 9")
                .replace("标题一", "挡板一")
                .replace("标题二", "挡板二")
                .replace("正文一", "挡板一")
                .replace("正文二", "挡板二")
                .replace("要点：判断与叙事不可外包 1", "挡板一")
                .replace("要点：判断与叙事不可外包 2", "挡板二"),
                encoding="utf-8",
            )
            subprocess.run(
                ["node", str(bad_script), str(ROOT), str(bad_deck)],
                cwd=str(ROOT),
                capture_output=True,
                text=True,
                encoding="utf-8",
                errors="replace",
                timeout=120,
                check=True,
            )
            fixture["pptx"] = bad_deck
            result = self._run_gate_all(root, fixture)
            self.assertEqual(2, result.returncode)
            merged = json.loads((root / "gate-all-report.json").read_text(encoding="utf-8"))
            self.assertFalse(merged["ok"])
            self.assertFalse(merged["steps"]["rendered"]["ok"])
            self.assertFalse(merged["steps"]["actual-content"]["ok"])
            self.assertFalse(merged["steps"]["quality"]["ok"])
            # 单步失败不拖垮其余步骤：package 与其余步骤仍有独立结论。
            self.assertIn("ok", merged["steps"]["package"])
            self.assertIn("ok", merged["steps"]["quality"])


if __name__ == "__main__":
    unittest.main()
